name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: print 1
       run: echo "Hello World"
     - name: print 2
       run: echo "Done, bye"
